#https://blog.flutterando.com.br/publicando-suas-paginas-flutter-no-github-pages-utilizando-github-action-ab2701cd1f52
name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email ${{secrets.email}}
          git config --global user.name guiofranca
          git status
          git remote add origin https://${{secrets.token}}@github.com/guiofranca/flutter-todo
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f